# for module compiling
import os
from building import *

cwd = GetCurrentDir()


CPPPATH = [cwd, str(Dir('#'))]
src = Glob('*.c')
group = DefineGroup('lvgl/port', src, depend = [''],CPPPATH = CPPPATH)


Return('group')
