from building import *
import rtconfig

cwd = GetCurrentDir()
list = os.listdir(cwd)
objs = []

src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('icon', src, depend = [''], CPPPATH = CPPPATH)


Return('group')
